[package]
name = "hallinta"
version = "0.8.6"
description = "Hallinta - Noita Mod Manager"
authors = ["kungfulife"]
edition = "2024"

[dependencies]
eframe = { version = "0.35.0", features = ["wgpu"] }
egui_extras = { version = "0.35.0", features = ["image"] }
rfd = "0.17.2"
opener = "0.8.5"
image = { version = "0.25.10", default-features = false, features = ["png"] }

serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"

dirs = "6.0.0"
tokio = { version = "1.52.3", features = ["rt-multi-thread", "sync", "time", "fs"] }
chrono = "0.4.45"
zip = "8.6.0"
named-lock = "0.4"
walkdir = "2.5.0"
sha2 = "0.11.0"
semver = "1.0.28"
self_update = { version = "=0.44.0", default-features = false, features = [
    "reqwest",
    "rustls",
    "archive-zip",
    "compression-zip-deflate",
    "signatures",
] }

[target.'cfg(windows)'.dependencies]
winreg = "0.56.0"

[build-dependencies]
winresource = "=0.1.31"

[package.metadata.winresource]
ProductName = "Hallinta"
FileDescription = "Hallinta - Noita Mod Manager"
InternalName = "Hallinta"
OriginalFilename = "Hallinta.exe"
CompanyName = "kungfulife"
